CREATE  TABLE `test`.`USER_REGISTRATION` (

  `AC_NO` VARCHAR(45) NOT NULL ,

  `AC_NAME` VARCHAR(45) NULL ,

  `AC_BRANCH` VARCHAR(45) NULL ,

  `AC_PWD` VARCHAR(45) NULL ,

  PRIMARY KEY (`AC_NO`) );

